# Project Information
site_name: Amon Documentation
site_author: Simplistic LLC.
site_favicon: 'assets/img/icon.png'
site_url: https://docs.amon.cx

# Repository
repo_name: 'GitHub'
repo_url: https://github.com/amonapp/amon

# Copyright
copyright: 'Copyright &copy; Simplistic LLC.'

# Theme
theme: 'material'
theme_dir: 'theme'
extra_css: ['assets/css/extra.css']
extra:
  logo: 'assets/img/icon.png'
  palette:
    primary: 'amon'
    accent: 'blue grey'
  font:
    text: 'Open Sans'
    code: 'Roboto Mono'
  author:
    github: 'amonapp'
    twitter: 'amonapp'

# Contents
pages:
  - Getting Started: 'index.md'
  - Monitoring Agent: 'agent.md'
  - Plugins: 'plugins.md'
  - Notifications: 'notifications.md'
  - Cloud Servers: 'cloudservers.md'
  - API: 'api.md'
  - On-Premise: 'onpremise.md'

# Analytics
google_analytics: ['UA-26305832-2', 'auto']

# Extensions
markdown_extensions:
  - toc(permalink=¶)
  - sane_lists:
  - admonition:
  - markdown_include.include:
